version: 2
jobs:
  build:
    working_directory: ~/bowerick
    docker:
      - image: circleci/clojure:lein-2.7.1
    environment:
      LEIN_ROOT=nbd
    steps:
      - checkout
      - restore_cache:
          key: << checksum "project.clj" >>
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: << checksum "project.clj" >>
      - run: lein do test, uberjar
      - store_artifacts:
          path: target/uberjar/bowerick.jar
          destination: uberjar
